### PR TITLE
273 Editing an experiment tag leads to blank page

### LINKED ISSUE #273: Editing an experiment tag leads to blank page
By editing an already existing experiment and trying to add a tag, as soon as the user clicks on the tag field it is redirected to a blank page with the following errors in the console

https://github.com/MetaCell/salk-interactive-atlas/assets/99416933/f88c995c-a254-4b6d-ae18-24e70e61e5c8

Steps to Reproduce:
1. Login
2. Create an experiment (or having an already created experiment)
3. Click on top of the experiment to open the submenu
4. Click on the Edit info and tags 
5. Add a new tag

### PR DESCRIPTION
**Pull request by Aiga115**
Closes #273

Implemented solution:
Displayed dialog window on card level, implemented on change function for each instance (name, desciption, tags), which changes the state, after calling the updateExperiment api we change the experiment then we call the function to call the experiments list again

### CODE REVIEW

File: applications/portal/frontend/src/components/home/ExplorationSpinalCordDialog.tsx [hunk 1]
```diff
@@ -36,35 +28,157 @@ const useStyles = makeStyles(() => ({
...
   const classes = useStyles();
-  const { open, handleClose } = props;
+  const commonClasses = common();
+  const api = WorkspaceService.getApi();
+  const { experimentId, experiment, tagsOptions, open, handleClose, refreshExperimentList, setExperimentMenuEl } = props;
+
+  const [name, setName] = React.useState<string>(experiment.name);
+  const [description, setDescription] = React.useState<string>(experiment.description);
+  const [validationErrors, setValidationErrors] = React.useState(new Set([]));
+  const [initialTags, setInitialTags] = React.useState(experiment.tags.map((t: any) => t.name));
```
Comment (afonsobspinto) [inline applications/portal/frontend/src/components/home/ExplorationSpinalCordDialog.tsx:53]: We don't need the initialTags state variable. You can, and it's probably better if you do (since it avoids consistency problems), just use the experiment.tags. 
After the experiment update, the new experiments fetch that happens will contain the experiment latest state with the latest tags - assuming the delete tags is working which doesn't seem like it is but I will investigate that myself

**Review by afonsobspinto — CHANGES_REQUESTED** [review]

**Review by afonsobspinto — APPROVED** [review]
Thanks :1st_place_medal:

**Review by zsinnema — APPROVED** [review]
