### PR TITLE
fix: #41 makes experiment cards configurable based on the experiment …

### LINKED ISSUE #41: Experiment card have 2 "types": one general type and one when the experiment is shared
The difference is the footer of the experiment card:
* one is with the creation date
* the other is with the shared with me date

### PR DESCRIPTION
**Pull request by paularah**
…type

Closes #41 

Implemented solution: ... 
@zsinnema The way I think of this. There are essentially 3 types of experiments i.e personal, shared and team. The styling for the experiment card differs. So my approach is passing a prop the tell what kind of experiment it is and then prop can be used to modify the styling or any other logic within the individual cards. This solution also accounts for the team's experiment card that is styled differently from the others
Screenshot from 2022-03-16 23-06-46

Screenshot from 2022-03-16 23-07-01
!

Screenshot from 2022-03-16 23-07-16

How to test this PR: ...

### Sanity checks:
- [x] The pull request is explicitly linked to the relevant issue(s)
- [x] The issue is well described: clearly states the problem and the general proposed solution(s)
- [ ] From the issue and the current PR it is explicitly stated how to test the current change
- [x] The labels in the issue set the scope and the type of issue (bug, feature, etc.)
- [x] All the automated test checks are passing
- [ ] All the linked issues are included in one milestone
- [x] All the linked issues are assigned

### Breaking changes (select one):
- [x] The present changes do not change the preexisting api in any way
- [ ] This PR and the issue are tagged as a `breaking-change`

### Possible deployment updates issues (select one):
- [x] There is no reason why deployments may break after the current update
- [ ] This PR and the issue are tagged as `alert:deployment`

### Test coverage (select one):
- [ ] Tests for the relevant cases are included in this pr
- [ ] The changes included in this pr are out of the current test coverage scope

### Documentation (select one):
- [ ] The documentation has been updated to match the current changes
- [x] The changes included in this PR are out of the current documentation scope

### Nice to have (if relevant):
- [] Screenshots of the changes
- [ ] Explanatory video/animated gif

### CODE REVIEW

File: applications/salk-portal/src/components/home/ExperimentCard.jsx [hunk 1]
```diff
@@ -114,7 +115,8 @@ const useStyles = makeStyles(() => ({
 
 const ExperimentCard = (props) => {
   const classes = useStyles();
-  const { tags, heading, description, user, i, community } = props;
+  const { tags, heading, description, user, i, community, type} = props;
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/ExperimentCard.jsx:118]: please merge the develop branch and (if there are) fix the merge conflicts

File: applications/salk-portal/src/components/home/ExperimentCard.jsx [hunk 2]
```diff
@@ -114,7 +115,8 @@ const useStyles = makeStyles(() => ({
...
+
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/ExperimentCard.jsx:119]: type is not being used here

File: applications/salk-portal/src/components/home/ExperimentList.jsx [hunk 3]
```diff
@@ -263,7 +265,7 @@ const ExperimentList = (props) => {
       <Box p={5}>
         <Grid container item spacing={3}>
           {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((item, i) => (
-            <ExperimentCard i={`${heading}experiment_${i}`} tags={tags} heading={"Exploration of the spinal cord"} description={"Shared on Sept 2nd, 2021"} user={"name"} />
+            <ExperimentCard i={`${heading}experiment_${i}`} type={type} tags={tags} heading={"Exploration of the spinal cord"} description={type == "personal" ? "Sept 2nd, 2021": "Shared on Sept 2nd, 2021"} user={"name"} />
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/ExperimentList.jsx:268]: why do you let the container decide what the heading and description is? This should be the responsibility of the card. 
also here I would pass in the experiment object and not all individual attributes. please also ask @vidhya-metacell what she thinks about this

**Review by zsinnema — CHANGES_REQUESTED** [review]

File: applications/salk-portal/src/components/home/ExperimentList.jsx (hunk 3 above)
Comment (vidhya-metacell) [reply applications/salk-portal/src/components/home/ExperimentList.jsx:268]: @paularah please create a dummy experiment object and pass here. Once you do that you can use the type to make the decision in the ExperimentCard rather than in the list. Also we are using the Experiment Card for communities as well which has in turn has different description and also an image on the corner. You would notice that decision is taken inside the the experiment card for community image display, in the same you can decide for the description in the card.

Comment (zsinnema) [reply applications/salk-portal/src/components/home/ExperimentList.jsx:268]: @paularah @vidhya-metacell there is already an Experiment type in apiclient/workspaces/api.ts ;-)

or even better create a new models/experiment.ts and extend it from apiclient/workspaces/api.ts Experiment

Comment (zsinnema) [reply applications/salk-portal/src/components/home/ExperimentList.jsx:268]: (it could be that you have to pull latest develop branch in your branch)

Comment (paularah) [reply applications/salk-portal/src/components/home/ExperimentList.jsx:268]: @zoran would this be a class that implements the experiment intecace defined in apiclient/workspaces/api.ts?

Comment (vidhya-metacell) [reply applications/salk-portal/src/components/home/ExperimentList.jsx]: @paularah @zsinnema there is actually a third type of description being used for experiments in community tab.
I will them here for reference:
my experiments - just the date
shared - 'Shared on' + date
community - number of clones

Comment (paularah) [reply applications/salk-portal/src/components/home/ExperimentList.jsx]: > @paularah @vidhya-metacell there is already an Experiment type in apiclient/workspaces/api.ts ;-)
> 
> or even better create a new models/experiment.ts and extend it from apiclient/workspaces/api.ts Experiment

@zsinnema maybe I am missing something, I can't find a type field on the experiment interface.

Comment (zsinnema) [reply applications/salk-portal/src/components/home/ExperimentList.jsx]: of course there is no type on the experiments interface, I meant there is already an `Experiment` class (type)

File: applications/salk-portal/src/models/ExperimentInstance.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
+import {Experiment, ExperimentOwner, ExperimentOwnerGroups, ExperimentCollaborators, ExperimentPopulations, ExperimentTags} from '../apiclient/workspaces/api'
+
+export default class ExperimentInstance implements Experiment {
```
Comment (zsinnema) [inline applications/salk-portal/src/models/ExperimentInstance.ts:3]: @paularah I would just extend the interface and use it for the object creation.

when you do implements then you need to (re)write the whole interface when the generated api interface changes. Using extends will make the code more "agile"

File: applications/salk-portal/src/components/home/ExperimentCard.jsx [hunk 5]
```diff
@@ -114,41 +114,42 @@ const useStyles = makeStyles(() => ({
 
 }));
 
-const ExperimentCard = (props) => {
+const ExperimentCard = ({experiment, type}) => {
+  console.log(experiment.name, experiment.date_created)
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/ExperimentCard.jsx:118]: please don't use console.log, use the debugger :-)

File: applications/salk-portal/src/components/home/Community.jsx [hunk 6]
```diff
@@ -164,7 +169,7 @@ const Community = () => {
         <Typography component="h2">Popular experiments</Typography>
         <Grid container item spacing={3}>
           {[1, 2, 3, 4].map((item, i) => (
-            <ExperimentCard i={`communityexperiment_${i}`} heading={"Exploration of the spinal cord"} description={"223 clones"} user={"name"} community={true} />
+            <ExperimentCard experiment={experiment} type="community" />
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/Community.jsx:172]: for fixed values please use enums or constants instead of strings. this makes the code more maintainable

File: applications/salk-portal/src/components/home/Community.jsx [hunk 7]
```diff
@@ -193,8 +198,8 @@ const Community = () => {
       <Box className={classes.wrapper}>
         <Typography component="h2">Last Published</Typography>
         <Grid container item spacing={3}>
-          {[1, 2, 3, 4].map((item, i) => (
-            <ExperimentCard i={`lastpublished_${i}`} heading={"Exploration of the spinal cord"} description={"223 clones"} user={"name"} community={true} />
+          {[1, 2, 3, 4].map(i => (
+            <ExperimentCard experiment={experiment} type="community"/>
```
Comment (zsinnema) [inline applications/salk-portal/src/components/home/Community.jsx:202]: same here

**Review by zsinnema — CHANGES_REQUESTED** [review]

**Review by zsinnema — CHANGES_REQUESTED** [review]
please revert the merge of develop

**Comment by paularah** [comment]
> please revert the merge of develop

@zsinnema I have done this

**Review by zsinnema — APPROVED** [review]
